apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minecraft-server
  namespace: argo-cd
spec:
  project: spof-cluster
  sources:
    - chart: minecraft-server
      repoURL: https://itzg.github.io/minecraft-server-charts/
      targetRevision: 4.15.0
      helm:
        releaseName: minecraft-server
        valueFiles:
          - $values/values.yaml
    - repoURL: 'https://github.com/SP0Fs/minecraft-server-k8s.git'
      targetRevision: HEAD
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: minecraft-server
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true