resources:
  limits:
    memory: 4096Mi
    cpu: 3.5

nodeSelector:
  kubernetes.io/hostname: c-nuc7

livenessProbe:
  initialDelaySeconds: 100
  periodSeconds: 10
  timeoutSeconds: 5
readinessProbe:
  initialDelaySeconds: 100
  periodSeconds: 10
  timeoutSeconds: 5

extraVolumes:
  - name: worldImport
    mountPath: /worldImport
    readOnly: true

    volumes: 
    - name: worldImport
      hostPath:
        path: /home/spof/minecraft

minecraftServer:
  eula: "true"
  version: "1.20.4"
  type: "FABRIC"
  difficulty: hard
  whitelist: Nicchus97,BadestFlopHD,user3,user4,XDawanX
  ops: Nicchus97
  maxPlayers: 6
  maxWorldSize: 100000
  allowNether: true
  announcePlayerAchievements: true
  enableCommandBlock: true
  forcegameMode: false
  generateStructures: true
  hardcore: false
  maxBuildHeight: 256
  maxTickTime: 60000
  spawnAnimals: true
  spawnMonsters: true
  spawnNPCs: true
  spawnProtection: 0
  viewDistance: 12
  #levelSeed: 2705254700866455343
  gameMode: survival
  pvp: true
  memory: ""
  downloadWorldUrl: /worldImport/stefansWorld/stefansWorld.zip
  forceReDownload: true

  modUrls: 
   - "https://cdn.modrinth.com/data/TQTTVgYE/versions/yYzR60Xd/fabric-carpet-1.20.3-1.4.128%2Bv231205.jar"
   - "https://cdn.modrinth.com/data/gvQqBUqZ/versions/nMhjKWVE/lithium-fabric-mc1.20.4-0.12.1.jar"
   - "https://cdn.modrinth.com/data/H8CaAYZC/versions/HZYU0kdg/starlight-1.1.3%2Bfabric.f5dcd1a.jar"
   - "https://cdn.modrinth.com/data/fQEb0iXm/versions/bRcuOnao/krypton-0.2.6.jar"
   - "https://cdn.modrinth.com/data/uXXizFIs/versions/pguEMpy9/ferritecore-6.0.3-fabric.jar"
   - "https://cdn.modrinth.com/data/Wnxd13zP/versions/jdeTwq6v/Clumps-fabric-1.20.4-15.0.0.2.jar"
   - "https://cdn.modrinth.com/data/NRjRiSSD/versions/5xvCCRjJ/memoryleakfix-fabric-1.17%2B-1.1.5.jar"
   - "https://cdn.modrinth.com/data/nmDcB62a/versions/Btq1HFzk/modernfix-fabric-5.13.0%2Bmc1.20.4.jar"
   - "https://cdn.modrinth.com/data/4WWQxlQP/versions/H1fXXdNC/servercore-fabric-1.4.0%2B1.20.3.jar"
   - "https://cdn.modrinth.com/data/P7dR8mSH/versions/9p2sguD7/fabric-api-0.96.4%2B1.20.4.jar"

  rcon:
    enabled: true
    withGeneratedPassword: false
    existingSecret: rcon-password-secret
    secretKey: password

extraEnv:
  INIT_MEMORY: 2G
  MAX_MEMORY: 4G

persistence:
  storageClass: manual
  dataDir:
    enabled: true
    existingClaim: minecraft-pvc

mcbackup:
  enabled: true
  persistence:
    #TODO: change to HDD when available and increase size
    storageClass: ssd
    backupDir:
      enabled: true
      Size: 10Gi
