apiVersion: v1
kind: PersistentVolume
metadata:
  name: minecraft-world-pv
  namespace: minecraft-server
  labels:
    type: local
spec:
  storageClassName: world-import
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/worldImport"