apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-world-pvc
  namespace: minecraft-server
spec:
  storageClassName: world-import
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
